### ISSUE TITLE
Preview text in unfolded links displays static content

### ISSUE THREAD

**Issue by arewm** [slsa-framework/slsa#693]
When pasting links to slsa.dev into common platforms that perform link unfurling, it would be great if a scoped and accurate description were displayed instead of every page having a description of 

> SLSA: Security framework to ensure software supply chain integrity 

I believe that this arises because the [default description](https://github.com/slsa-framework/slsa/blob/1fd20a9a9b76b4eba3e9565edcd2d94eccfd5ba1/docs/_config.yml#L2) is always used since it is never specified in the [YAML frontmatter](https://github.com/slsa-framework/slsa/blob/1fd20a9a9b76b4eba3e9565edcd2d94eccfd5ba1/docs/_includes/specifications-list.html#L7-L15). 

```yaml
    ---
    subpages:
      - title: Some page
        description: Text to display below the link
        relative_url: foo
      - title: Another page
        description: More text
        relative_url: ../bar
    ---
```

I believe that if we add a `description` to all pages that the preview text should be customized in link unfurling. 

This is further supported by inspecting the HTML on pages and finding
```html
<meta property="og:description" content="SLSA: Security framework to ensure software supply chain integrity">
```
Additionally, if you _wanted_ to specify a different image for the page's link unfurling, I assume that that would be accomplished via the HTML tag

```html
<meta property="og:image" content="http://slsa.dev/images/icons/android-chrome-192x192.png">
```

The related markup is `og:*`: https://ogp.me/
