### ISSUE TITLE
v1 VSA: Update policy levels to indicate the track

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa#725]
In VSA https://slsa.dev/verification_summary/v1

The policy levels don't indicate the track: `build`, `source`. It would be useful to add the track information. Possible options:

### Add a nested track field
```yaml
"policy_levels": {
  "build": "SLSA_LEVEL_3",
  "source": "SLSA_LEVEL_3",
  ...
}
```

### Add track in policy_level
```yaml
"policy_source_level": "SLSA_LEVEL_3",
"policy_build_level": "SLSA_LEVEL_3",
```

### Same as above + rename level
```yaml
"policy_source_level": "SLSA_SOURCE_LEVEL_3",
"policy_build_level": "SLSA_BUILD_LEVEL_3",
```
